export const CART_ADD_PRODUCT = 'CARD_ADD_PRODUCT'
export const CART_REMOVE_PRODUCT = 'CARD_REMOVE_PRODUCT'
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'